# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jakub/C++/Kasyno/Casino

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jakub/C++/Kasyno/Casino

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jakub/C++/Kasyno/Casino/CMakeFiles /home/jakub/C++/Kasyno/Casino//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jakub/C++/Kasyno/Casino/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CasinoGames

# Build rule for target.
CasinoGames: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CasinoGames
.PHONY : CasinoGames

# fast build rule for target.
CasinoGames/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/build
.PHONY : CasinoGames/fast

#=============================================================================
# Target rules for targets named clean_target

# Build rule for target.
clean_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_target
.PHONY : clean_target

# fast build rule for target.
clean_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_target.dir/build.make CMakeFiles/clean_target.dir/build
.PHONY : clean_target/fast

#=============================================================================
# Target rules for targets named pack

# Build rule for target.
pack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pack
.PHONY : pack

# fast build rule for target.
pack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pack.dir/build.make CMakeFiles/pack.dir/build
.PHONY : pack/fast

dicePoker.o: dicePoker.cpp.o
.PHONY : dicePoker.o

# target to build an object file
dicePoker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/dicePoker.cpp.o
.PHONY : dicePoker.cpp.o

dicePoker.i: dicePoker.cpp.i
.PHONY : dicePoker.i

# target to preprocess a source file
dicePoker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/dicePoker.cpp.i
.PHONY : dicePoker.cpp.i

dicePoker.s: dicePoker.cpp.s
.PHONY : dicePoker.s

# target to generate assembly for a file
dicePoker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/dicePoker.cpp.s
.PHONY : dicePoker.cpp.s

gameInfo.o: gameInfo.cpp.o
.PHONY : gameInfo.o

# target to build an object file
gameInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/gameInfo.cpp.o
.PHONY : gameInfo.cpp.o

gameInfo.i: gameInfo.cpp.i
.PHONY : gameInfo.i

# target to preprocess a source file
gameInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/gameInfo.cpp.i
.PHONY : gameInfo.cpp.i

gameInfo.s: gameInfo.cpp.s
.PHONY : gameInfo.s

# target to generate assembly for a file
gameInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/gameInfo.cpp.s
.PHONY : gameInfo.cpp.s

hangman.o: hangman.cpp.o
.PHONY : hangman.o

# target to build an object file
hangman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/hangman.cpp.o
.PHONY : hangman.cpp.o

hangman.i: hangman.cpp.i
.PHONY : hangman.i

# target to preprocess a source file
hangman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/hangman.cpp.i
.PHONY : hangman.cpp.i

hangman.s: hangman.cpp.s
.PHONY : hangman.s

# target to generate assembly for a file
hangman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/hangman.cpp.s
.PHONY : hangman.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/main.cpp.s
.PHONY : main.cpp.s

opponent.o: opponent.cpp.o
.PHONY : opponent.o

# target to build an object file
opponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/opponent.cpp.o
.PHONY : opponent.cpp.o

opponent.i: opponent.cpp.i
.PHONY : opponent.i

# target to preprocess a source file
opponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/opponent.cpp.i
.PHONY : opponent.cpp.i

opponent.s: opponent.cpp.s
.PHONY : opponent.s

# target to generate assembly for a file
opponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/opponent.cpp.s
.PHONY : opponent.cpp.s

player.o: player.cpp.o
.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i
.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s
.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/player.cpp.s
.PHONY : player.cpp.s

tarot.o: tarot.cpp.o
.PHONY : tarot.o

# target to build an object file
tarot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/tarot.cpp.o
.PHONY : tarot.cpp.o

tarot.i: tarot.cpp.i
.PHONY : tarot.i

# target to preprocess a source file
tarot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/tarot.cpp.i
.PHONY : tarot.cpp.i

tarot.s: tarot.cpp.s
.PHONY : tarot.s

# target to generate assembly for a file
tarot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/tarot.cpp.s
.PHONY : tarot.cpp.s

ticTacToe.o: ticTacToe.cpp.o
.PHONY : ticTacToe.o

# target to build an object file
ticTacToe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/ticTacToe.cpp.o
.PHONY : ticTacToe.cpp.o

ticTacToe.i: ticTacToe.cpp.i
.PHONY : ticTacToe.i

# target to preprocess a source file
ticTacToe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/ticTacToe.cpp.i
.PHONY : ticTacToe.cpp.i

ticTacToe.s: ticTacToe.cpp.s
.PHONY : ticTacToe.s

# target to generate assembly for a file
ticTacToe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CasinoGames.dir/build.make CMakeFiles/CasinoGames.dir/ticTacToe.cpp.s
.PHONY : ticTacToe.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clean_target"
	@echo "... pack"
	@echo "... CasinoGames"
	@echo "... dicePoker.o"
	@echo "... dicePoker.i"
	@echo "... dicePoker.s"
	@echo "... gameInfo.o"
	@echo "... gameInfo.i"
	@echo "... gameInfo.s"
	@echo "... hangman.o"
	@echo "... hangman.i"
	@echo "... hangman.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... opponent.o"
	@echo "... opponent.i"
	@echo "... opponent.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... tarot.o"
	@echo "... tarot.i"
	@echo "... tarot.s"
	@echo "... ticTacToe.o"
	@echo "... ticTacToe.i"
	@echo "... ticTacToe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

